### ISSUE TITLE
LeftClickSelect doesn't work with Better Combat

### ISSUE THREAD

**Issue by elykfox** [TrueHorse/Wild-Tool-Access#1]
popening the hud works but selecting the tool or item in left click doesnt work

**Comment by TrueHorse** [comment]
Do you have any additional information, that you think could be useful? Did it consistently not work, did the sound play, stuff like that? Sometimes it seems to select the wrong item, or non at all, but I havn't figured out what causes that yet.

**Comment by GermanArtur** [comment]
This bug exists when mod installed with BetterCombat mod. It is impossible to select a tool with the left mouse button when the weapon is in the active slot.

**Comment by TrueHorse** [comment]
@GermanArtur I don't think that that was his problem, but he doesn't respond anymore, so let's pretend it was.

**Comment by TrueHorse** [comment]
Okay, issue should be fixed in the next update.
