### ISSUE TITLE
Add a function that locks tool swap to a specific slot on the hotbar

### ISSUE THREAD

**Issue by DonkoKonko** [TrueHorse/Wild-Tool-Access#12]
If a player wants their tools to only be in the first hotbar slot, any tool selected in the toolbar will be placed in the first hotbar slot even if the 2nd, 3rd, 4th, etc. item in the hotbar is currently held. In this instance, when a tool is selected using the mod, the 1st slot in the hotbar will be automatically switched to as if the player pressed "1" on the keyboard the instant the tool was swapped out.

**Comment by TrueHorse** [comment]
Sounds like it could be useful and should be easy to implement, so I think I will add it with the next update.

**Comment by TrueHorse** [comment]
Update is released. I split it up into two different options for maximum flexibility ;). There is also a 1.19.4 version relatively ready, but I want to wait for the official release of 1.19.4.
