### ISSUE TITLE
Ability to add tags to Stuff

### ISSUE THREAD

**Issue by ahowell610** [TrueHorse/Wild-Tool-Access#20]
So I was hoping to be able to have the ability to just specify a tag (ex. forge:tools/pickaxes) in the "Stuff" category and it could read all items in that tag and allow them to be cycled through. This would just allow for mod pack makers to increase compatibility in way way less time

**Comment by TrueHorse** [comment]
That makes sence. Thank you for the suggestion. 🙂 When I first made this mod I only looked at vanilla tags, didn't find them useful and just checked tags of in my mind entirely.
If I ever feel like adding features to this mod again, this will probably be the first.
