### ISSUE TITLE
Possibility for in-game configuration menu on Forge/NeoForge versions?

### ISSUE THREAD

**Issue by NovaViper** [TrueHorse/Wild-Tool-Access#26]
Hey, I'm wondering there are any plans to implement an in-game configuration menu for the Forge/NeoForge versions of Wild Tool Access. There's a couple of options that can be used:
- [YetAnotherConfigLib](https://modrinth.com/mod/yacl), works on Forge up until 1.20.1, and all NeoForge versions (and even Fabric!) that this mod supports
- [Configured](https://www.curseforge.com/minecraft/mc-mods/configured), works on all versions of NeoForge, Forge, and Fabric that this mod supports

**Comment by TrueHorse** [comment]
Thank you for the extensive question. Makes me sorry to say, that that is just a result of me not bothering to find out how I make the Forge config button open the config screen, I already made for Mod Menu using Cloth Config, which has a Forge version. 😅
Going to look into it. 🙂
