### ISSUE TITLE
Crash when used with EssentialClient

### ISSUE THREAD

**Issue by HoldYourWaffle** [TrueHorse/Wild-Tool-Access#3]
The game crashes at startup when this mod is installed alongside [EssentialClient](https://github.com/senseiwells/EssentialClient) :(
Here's the [crash log](https://github.com/TrueHorse/Wild-Tool-Access/files/8918786/crash-2022-06-16_14.08.19-client.txt) for all the nasty details :)

**Comment by TrueHorse** [comment]
Sorry, that it is taking so long. I am having some unrelated technical issues.

**Comment by TrueHorse** [comment]
Ok, I am finally done now. Issue is fixed in 1.0.2.
