### ISSUE TITLE
Shears not seen

### ISSUE THREAD

**Issue by SebSemos** [TrueHorse/Wild-Tool-Access#9]
What the title says ^^ I know they are useless of a tool so maybe this is intended... :p 
And notice same goes for Flint and steel (and spyglass?)

**Comment by TrueHorse** [comment]
The reason for that is that, if you have "typeToAccess" set to tool, it shows you all items, that derive from the class ToolItem and shears don't. If that doesn't tell you anything, then let's just say, that shear are not in the group "tool" in the Minecraft code and that is all this mod checks for.
I don't intend to change that, so you would have to use the stuff tag, if you would want to access them through the access bars. If you would want to access all tools+shears etc. with one bar you would have to put all tools in the stuff tag too though, so I should probably add the option to use the stuff tag+a predefined type at once in one bar.
Would you be okay with me repurposing this issue for that?

**Comment by SebSemos** [comment]
I understand. It's weird how mojang isn't consistent at all because these are in the "tool" tab in the creative menu ^^ I think it's not worth the troubble to fix this. 
Shears are useless, espacially now hoes are able to instamine leaves. Shears are only good for wool now, wich in not often present in huge quantity so... ^^

**Comment by TrueHorse** [comment]
Thank you for that understanding. 🙂
